name: Auto-release specific changes

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      # https://github.com/actions/checkout
      - name: Cloning ${{ env.GIT_BRANCH }} branch
        uses: actions/checkout@v2-beta
        with:
          ref: master

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set up gh CLI tool
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh auth status

      - name: Show the most recent changes
        run: |
          git status
          git log -n 1

      # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      - name: Take the latest commit message
        id: commit-message
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          # -r		output raw strings, not JSON texts;
          export COMMIT_MESSAGE=$(echo "$GITHUB_CONTEXT" | jq -r .event.head_commit.message | head -n1)

          set -x
          echo "::set-output name=commit-message::${COMMIT_MESSAGE}"
          echo "::notice::Got the commit message: ${COMMIT_MESSAGE}"

      - name: Automatically create a patch release
        # e.g. Updating rules/prefixes.json (#416)
        if: contains( steps.commit-message.outputs.commit-message , 'Updating rules/prefixes.json' )
        run: |
          npm run bump-version-patch
