name: CSS prefixes

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      GIT_BRANCH: "devel"
      GIT_USER_NAME: "macbre"
      GIT_USER_EMAIL: "<macbre@users.noreply.github.com>"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2-beta
        with:
          ref: ${GIT_BRANCH}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Update prefixes
        run: |
          npm ci
          npm run prefixes

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set up git
        run: |
          git config user.name ${GIT_USER_NAME}
          git config user.email ${GIT_USER_EMAIL}

      - name: Show a diff
        run: |
          git diff
          git add .

      - name: Commit if needed
        continue-on-error: true
        run: |
          git commit -m 'Updating rules/prefixes.json' && git push origin ${GIT_BRANCH}
